# Getting started

In [1]:
# do basic imports and unpack McMurdo data

from pmagpy import ipmag
from programs import new_builder as nb
from programs import data_model3
import os
import pandas as pd
from pandas import DataFrame
from programs.new_builder import Contribution

wdir = os.path.join(os.getcwd(), "3_0", "McMurdo")
infile = os.path.join(wdir, "lawrence09.v30.txt")
ipmag.download_magic(infile, overwrite=True)

/Users/nebula/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/matplotlib/__init__.py:1350: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)

working on:  'contribution'
1  records written to file  ./contribution.txt
contribution  data put in  ./contribution.txt
working on:  'locations'
5  records written to file  ./locations.txt
locations  data put in  ./locations.txt
working on:  'sites'
391  records written to file  ./sites.txt
sites  data put in  ./sites.txt
working on:  'samples'
1418  records written to file  ./samples.txt
samples  data put in  ./samples.txt
working on:  'specimens'
1374  records written to file  ./specimens.txt
specimens  data put in  ./specimens.txt
working on:  'measurements'
25470  records written to file  ./measurements.txt
measurements  data put in  ./measurements.txt
working on:  'ages'
99  records written to file  ./ages.txt
ages  data put in  ./ages.txt
working on:  'images'
431  records written to file  ./images.txt
images  data put in  ./images.txt
working on:  'criteria'
24  records written to file  ./criteria.txt
criteria  data put in  ./criteria.txt
location_1:  McMurdo
directory  ./Location_1  already exists - overwriting everything: True
unpacking:  ./contribution.txt
1  read in
unpacking:  ./locations.txt
5  read in
5  records written to file  ./Location_1/locations.txt
5  stored in  ./Location_1/locations.txt
unpacking:  ./sites.txt
391  read in
391  records written to file  ./Location_1/sites.txt
391  stored in  ./Location_1/sites.txt
unpacking:  ./samples.txt
1418  read in
unpacking:  ./specimens.txt
1374  read in
unpacking:  ./measurements.txt
25470  read in
unpacking:  ./ages.txt
99  read in
unpacking:  ./images.txt
431  read in
unpacking:  ./criteria.txt
24  read in
location_2:  McMurdo
directory  ./Location_2  already exists - overwriting everything: True
unpacking:  ./contribution.txt
1  read in
unpacking:  ./locations.txt
5  read in
5  records written to file  ./Location_2/locations.txt
5  stored in  ./Location_2/locations.txt
unpacking:  ./sites.txt
391  read in
391  records written to file  ./Location_2/sites.txt
391  stored in  ./Location_2/sites.txt
unpacking:  ./samples.txt
1418  read in
unpacking:  ./specimens.txt
1374  read in
unpacking:  ./measurements.txt
25470  read in
unpacking:  ./ages.txt
99  read in
unpacking:  ./images.txt
431  read in
unpacking:  ./criteria.txt
24  read in
location_3:  McMurdo
directory  ./Location_3  already exists - overwriting everything: True
unpacking:  ./contribution.txt
1  read in
unpacking:  ./locations.txt
5  read in
5  records written to file  ./Location_3/locations.txt
5  stored in  ./Location_3/locations.txt
unpacking:  ./sites.txt
391  read in
391  records written to file  ./Location_3/sites.txt
391  stored in  ./Location_3/sites.txt
unpacking:  ./samples.txt
1418  read in
unpacking:  ./specimens.txt
1374  read in
unpacking:  ./measurements.txt
25470  read in
unpacking:  ./ages.txt
99  read in
unpacking:  ./images.txt
431  read in
unpacking:  ./criteria.txt
24  read in
location_4:  McMurdo
directory  ./Location_4  already exists - overwriting everything: True
unpacking:  ./contribution.txt
1  read in
unpacking:  ./locations.txt
5  read in
5  records written to file  ./Location_4/locations.txt
5  stored in  ./Location_4/locations.txt
unpacking:  ./sites.txt
391  read in
391  records written to file  ./Location_4/sites.txt
391  stored in  ./Location_4/sites.txt
unpacking:  ./samples.txt
1418  read in
unpacking:  ./specimens.txt
1374  read in
unpacking:  ./measurements.txt
25470  read in
unpacking:  ./ages.txt
99  read in
unpacking:  ./images.txt
431  read in
unpacking:  ./criteria.txt
24  read in
location_5:  McMurdo
directory  ./Location_5  already exists - overwriting everything: True
unpacking:  ./contribution.txt
1  read in
unpacking:  ./locations.txt
5  read in
5  records written to file  ./Location_5/locations.txt
5  stored in  ./Location_5/locations.txt
unpacking:  ./sites.txt
391  read in
391  records written to file  ./Location_5/sites.txt
391  stored in  ./Location_5/sites.txt
unpacking:  ./samples.txt
1418  read in
unpacking:  ./specimens.txt
1374  read in
unpacking:  ./measurements.txt
25470  read in
unpacking:  ./ages.txt
99  read in
unpacking:  ./images.txt
431  read in
unpacking:  ./criteria.txt
24  read in

True

# Demo several ways of creating a contribution

In [2]:
reload(nb)

# test out various ways of creating a contribution

# make contribution with all defaults from working directory
con = nb.Contribution(wdir)
print con
print 'tables created:', con.tables.keys()

# make contribution with some custom filenames
con = nb.Contribution(wdir, custom_filenames={'specimens': 'custom_specimens.txt'})
print con
print 'tables created:', con.tables.keys()

# make contribution with custom filenames, and only specimen table to start
con = Contribution(wdir, read_tables=['specimens'], custom_filenames={'sites': 'crazy_site_file.txt',
                                                                  'specimens': 'custom_specimens.txt'})
print con
print 'tables created:', con.tables.keys()

# make contribution with a single, mystery file
con = nb.Contribution(wdir, single_file='sites.txt')
print con
print 'tables created:', con.tables.keys()

# make contribution with a single mystery file 
con = Contribution(wdir, single_file='custom_specimens.txt')
print con
print 'tables_created:', con.tables.keys()

filename /Users/nebula/Python/PmagPy/3_0/McMurdo/measurements.txt
filename /Users/nebula/Python/PmagPy/3_0/McMurdo/specimens.txt
-W- No such file: /Users/nebula/Python/PmagPy/3_0/McMurdo/specimens.txt
filename /Users/nebula/Python/PmagPy/3_0/McMurdo/samples.txt
-W- No such file: /Users/nebula/Python/PmagPy/3_0/McMurdo/samples.txt
filename /Users/nebula/Python/PmagPy/3_0/McMurdo/sites.txt
filename /Users/nebula/Python/PmagPy/3_0/McMurdo/locations.txt
filename /Users/nebula/Python/PmagPy/3_0/McMurdo/contribution.txt
filename /Users/nebula/Python/PmagPy/3_0/McMurdo/criteria.txt
filename /Users/nebula/Python/PmagPy/3_0/McMurdo/ages.txt
filename /Users/nebula/Python/PmagPy/3_0/McMurdo/images.txt
<programs.new_builder.Contribution object at 0x103e111d0>
tables created: ['measurements', 'ages', 'sites', 'locations', 'criteria', 'images', 'contribution']
filename /Users/nebula/Python/PmagPy/3_0/McMurdo/measurements.txt
filename /Users/nebula/Python/PmagPy/3_0/McMurdo/custom_specimens.txt
filename /Users/nebula/Python/PmagPy/3_0/McMurdo/samples.txt
-W- No such file: /Users/nebula/Python/PmagPy/3_0/McMurdo/samples.txt
filename /Users/nebula/Python/PmagPy/3_0/McMurdo/sites.txt
filename /Users/nebula/Python/PmagPy/3_0/McMurdo/locations.txt
filename /Users/nebula/Python/PmagPy/3_0/McMurdo/contribution.txt
filename /Users/nebula/Python/PmagPy/3_0/McMurdo/criteria.txt
filename /Users/nebula/Python/PmagPy/3_0/McMurdo/ages.txt
filename /Users/nebula/Python/PmagPy/3_0/McMurdo/images.txt
<programs.new_builder.Contribution object at 0x10df2f410>
tables created: ['measurements', 'ages', 'sites', 'locations', 'criteria', 'images', 'contribution', 'specimens']
filename /Users/nebula/Python/PmagPy/3_0/McMurdo/custom_specimens.txt
<programs.new_builder.Contribution object at 0x10df2f790>
tables created: ['specimens']
dtype sites
self.tables.keys() ['sites']
<programs.new_builder.Contribution object at 0x10cebb8d0>
tables created: ['sites']
dtype specimens
self.tables.keys() ['specimens']
<programs.new_builder.Contribution object at 0x10df2f410>
tables_created: ['specimens']

# Demonstrate functionality with a contribution

In [3]:
# create full McMurdo contribution

reload(nb)

con = nb.Contribution(wdir, custom_filenames={'specimens': 'custom_specimens.txt', 'samples': 'custom_samples.txt'})

filename /Users/nebula/Python/PmagPy/3_0/McMurdo/measurements.txt
filename /Users/nebula/Python/PmagPy/3_0/McMurdo/custom_specimens.txt
filename /Users/nebula/Python/PmagPy/3_0/McMurdo/custom_samples.txt
filename /Users/nebula/Python/PmagPy/3_0/McMurdo/sites.txt
filename /Users/nebula/Python/PmagPy/3_0/McMurdo/locations.txt
filename /Users/nebula/Python/PmagPy/3_0/McMurdo/contribution.txt
filename /Users/nebula/Python/PmagPy/3_0/McMurdo/criteria.txt
filename /Users/nebula/Python/PmagPy/3_0/McMurdo/ages.txt
filename /Users/nebula/Python/PmagPy/3_0/McMurdo/images.txt

### Dealing with criteria

In [4]:
#  grab a copy of the criteria and sites table to play with
criteria = con.tables['criteria'].df.copy()
sites = con.tables['sites'].df.copy()
sites.head()

,age,age_sigma,age_unit,analyst_names,citations,criteria_names,description,dir_alpha95,dir_comp_name,dir_dec,...,vadm_n_samples,vadm_sigma,vdm,vdm_n_samples,vdm_sigma,vgp_dm,vgp_dp,vgp_lat,vgp_lon,vgp_n_samples
site_name,,,,,,,,,,,,,,,,,,,,,
mc01,1.18,0.005,Ma,@ltauxe,This study,DE-SPEC,Direction included in Pmag_Results.,4.2,A,258.6,...,None,None,None,None,None,None,None,None,None,None
mc01,1.18,0.005,Ma,@ltauxe,This study,IE-SPEC,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
mc01,1.18,0.005,Ma,@klawrenc,This study,DE-SITE,"VGP: Site (geog. coord) A comp: mc01, Site VGP...",4.2,A,258.6,...,None,None,None,None,None,4.5,8.1,-67.3,95.2,7
mc02,0.33,0.01,Ma,@ltauxe,This study,DE-SPEC,Direction included in Pmag_Results.,2.1,A,328.6,...,None,None,None,None,None,None,None,None,None,None
mc02,0.33,0.01,Ma,@klawrenc,This study,DE-SITE,"VGP: Site (geog. coord) A comp: mc02, Site VGP...",2.1,A,328.6,...,None,None,None,None,None,2.5,4.1,79,101.2,6

In [5]:
# get all criteria for sites

# only criteria with 'site' in table_column_name
cond = criteria.index.str.contains('site')
site_crit = criteria[cond].copy()
# remove table name from index
site_crit.index = site_crit.index.str.replace('sites.', '')
site_crit.index.name = 'column_name'


cols = site_crit.index

In [6]:
sites.head()[cols]

,dir_alpha95,dir_n_samples,dir_n_specimens_lines,dir_k,int_abs_sigma,int_abs_sigma_perc,int_n_samples,dir_polarity,dir_polarity
site_name,,,,,,,,,
mc01,4.2,7,6,215.9,None,None,None,r,r
mc01,None,None,None,None,0.000003374,20.4,4,None,None
mc01,4.2,7,None,215.9,None,None,None,None,None
mc02,2.1,6,5,1079.2,None,None,None,n,n
mc02,2.1,6,None,1079.2,None,None,None,None,None

In [7]:
# create string --> operator conversion    
import operator
ops = {"<": operator.lt, ">": operator.gt, "==": operator.eq, "<=": operator.le, ">=": operator.gt}

# function for applying criteria
def apply_crit(series, crit_series, criteria_type):
    """
    Apply 1 criterion (i.e., 1 row of the criteria table) to another table.
    Return series with boolean values for whether the row passes.
    """
    col_name = crit_series.name
    #print col_name
    # if there's no value, pass == True??  or == False?
    if not series[col_name]:
        return "{} not in row".format(col_name)
    # if we're missing criteria names, then what??
    elif not series['criteria_names']:
        return "no value in criteria_names"
    elif criteria_type not in series['criteria_names']:
        return "{} not in criteria_names for this row".format(criteria_type)
    crit_name = crit_series['criterion_name']
    crit_value = float(crit_series['criterion_value'])
    op_str = crit_series['criterion_operation']
    op = ops[op_str]
    value = float(series[col_name])
    #print value, op_str, crit_value
    result = op(value, crit_value)
    #print op
    #print result
    return result

In [8]:
# apply a criterion to a table
crit_name = 'dir_alpha95'
pass_name = 'pass_' + crit_name
crit1 = site_crit.ix[crit_name]
sites[pass_name] = sites.apply(apply_crit, axis=1, args=(crit1, 'DE-SITE'))
cond = sites[pass_name] == True
sites[cond][[crit_name, pass_name]].head()

          dir_alpha95 pass_dir_alpha95
site_name
mc01              4.2             True
mc02              2.1             True
mc03              2.3             True
mc04              4.6             True
mc06              4.8             True

In [9]:
for crit_name in site_crit.index[1:]:
    crit_series = site_crit.ix[crit_name]
    # if there are multiple records for a single crit_name, ignore that one
    if not isinstance(crit_series, pd.Series):
        continue
    sites['pass_' + crit_name] = sites.apply(apply_crit, axis=1, args=(crit_series, "DE-SITE"))

    
cond = sites.columns.str.contains('pass')
sites.head()
sites[sites.columns[cond]].head()

,pass_dir_alpha95,pass_dir_n_samples,pass_dir_n_specimens_lines,pass_dir_k,pass_int_abs_sigma,pass_int_abs_sigma_perc,pass_int_n_samples
site_name,,,,,,,
mc01,DE-SITE not in criteria_names for this row,DE-SITE not in criteria_names for this row,DE-SITE not in criteria_names for this row,DE-SITE not in criteria_names for this row,int_abs_sigma not in row,int_abs_sigma_perc not in row,int_n_samples not in row
mc01,dir_alpha95 not in row,dir_n_samples not in row,dir_n_specimens_lines not in row,dir_k not in row,DE-SITE not in criteria_names for this row,DE-SITE not in criteria_names for this row,DE-SITE not in criteria_names for this row
mc01,True,True,dir_n_specimens_lines not in row,True,int_abs_sigma not in row,int_abs_sigma_perc not in row,int_n_samples not in row
mc02,DE-SITE not in criteria_names for this row,DE-SITE not in criteria_names for this row,DE-SITE not in criteria_names for this row,DE-SITE not in criteria_names for this row,int_abs_sigma not in row,int_abs_sigma_perc not in row,int_n_samples not in row
mc02,True,True,dir_n_specimens_lines not in row,True,int_abs_sigma not in row,int_abs_sigma_perc not in row,int_n_samples not in row

### Merging in data from other tables

In [10]:
spec_container = con.tables['specimens']
spec_df = spec_container.df

samp_container = con.tables['samples']
samp_df = samp_container.df

site_container = con.tables['sites']
site_df = site_container.df
site_df.ix[[0]]
spec_df.ix[[0]]
samp_df.ix[[0]]

spec_df[['sample_name']].head()

              sample_name
specimen_name
mc01a               mc01a
mc01a               mc01a
mc01b               mc01b
mc01b               mc01b
mc01c               mc01c

In [11]:
#  merge site_names into specimen table (from sample table)
#  (this snippet has been incorporated into new_builder)

if 'site_name' not in spec_df.columns:
    spec_df = spec_df.merge(samp_df[['site_name']], left_on=['sample_name'], right_index=True, how="left")
        
spec_df.head()[['sample_name', 'site_name']]
#new_df[new_df['site_name_x'] != new_df['site_name_y']]

              sample_name site_name
specimen_name
mc01a               mc01a      mc01
mc01a               mc01a      mc01
mc01b               mc01b      mc01
mc01b               mc01b      mc01
mc01c               mc01c      mc01

In [15]:
# how to update a dictionary:

standard_filenames = {'measurements': 'measurements.txt', 'ages': 'ages.txt', 'sites': 'sites.txt', 'locations': 'locations.txt', 'samples': 'samples.txt', 'criteria': 'criteria.txt', 'images': 'images.txt', 'contribution': 'contribution.txt', 'specimens': 'specimens.txt'}
filenames = {'sites': 'crazy_site_file.txt'}
standard_filenames.update(filenames)

# Putting some pieces together

In [13]:

reload(nb)
from programs.new_builder import Contribution

# build a contribution with several custom filenames
# only build sites table to start
con2 = Contribution(wdir, read_tables=['sites'], custom_filenames={'specimens': 'custom_specimens.txt', 
                                                                   'samples': 'custom_samples.txt'})
print con2.tables
# then add 'samples' table (no need to specify the filename here)
# we are providing data type but no filename
con2.add_magic_table('samples')
print con2.tables
# add site names
con2.add_site_names_to_specimen_table()
#con2.add_magic_table('fake')

# specimens table now has sample AND site names
con2.tables['specimens'].df[['sample_name', 'site_name']].head()

filename /Users/nebula/Python/PmagPy/3_0/McMurdo/sites.txt
{'sites': <programs.new_builder.MagicDataFrame object at 0x10df2f290>}
filename /Users/nebula/Python/PmagPy/3_0/McMurdo/custom_samples.txt
{'sites': <programs.new_builder.MagicDataFrame object at 0x10df2f290>, 'samples': <programs.new_builder.MagicDataFrame object at 0x10df2ff90>}
trying to add site_name
filename /Users/nebula/Python/PmagPy/3_0/McMurdo/custom_specimens.txt
samp_container 1418
self.tables.keys() at end of add_site_names ['specimens', 'sites', 'samples']

              sample_name site_name
specimen_name
mc01a               mc01a      mc01
mc01a               mc01a      mc01
mc01b               mc01b      mc01
mc01b               mc01b      mc01
mc01c               mc01c      mc01

In [14]:
# add another table to the same contribution
# this time, provide a filename but no data type

con2.add_magic_table(dtype="unknown", fname="criteria.txt")
# criteria table now included
print con2.tables.keys()

dtype criteria
['specimens', 'sites', 'samples', 'criteria']